version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://glints-backend.eastasia.cloudapp.azure.com
